# Generated by Django 5.0.6 on 2024-08-04 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_transaction_delete_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
